= Windows Network Drive Configuration

Here are the steps to configure WND in the Appliance.

== WND Listener

First you have to create a service following the instructions below that checks the share for changes:


  * Place one copy of this file for each mount point configuration (SERVER and
    SHARE) under
    `/etc/systemd/system/owncloud-wnd-listen-SERVER-SHARE.service` replacing the all upper case words `SERVER`, `SHARE`, `USER` and `PASSWORD` in both,
    the **filename** and in the **contents** below with their respective values.
    Take care to also adjust the paths in `WorkingDirectory` and `ExecStart`
    according to your installation.

    ....
    [Unit]
    Description=ownCloud WND Listener for SERVER SHARE
    After=docker-app-owncloud.service
    Requires=docker-app-owncloud.service
    [Service]
    User=root
    Group=root
    WorkingDirectory=/root
    ExecStart=/usr/bin/univention-app shell owncloud occ wnd:listen -vvv SERVER SHARE USER PASSWORD
    Type=simple
    StandardOutput=journal
    StandardError=journal
    SyslogIdentifier=%n
    KillMode=process
    RestartSec=1
    Restart=always
    ....


  * Then run once for each created file the following commands:

    systemctl enable owncloud-wnd-listen-SERVER-SHARE.service
    systemctl start  owncloud-wnd-listen-SERVER-SHARE.service

  * Make a crontab entry to run a script iterating over all `SERVER SHARE` pairs with
    an appropriate `occ wnd:process-queue` command. The commands must be **strictly sequentially**.
    This can be done by using `flock -n` and tuning the `-c` parameter of `occ wnd:process-queue`

== WND Process Queue

Then add a crontab file in /etc/cron.d/oc-wnd-process-queue

....
* * * * *     root  /usr/bin/univention-app shell owncloud occ wnd:process-queue -vvv DOMAIN SHARE
....


[NOTE]

You will need both of these files for each share .

See also:

https://central.owncloud.org/t/wnd-listener-configuration/3114[ownCloud forum]


https://doc.owncloud.org/server/10.0/admin_manual/enterprise/external_storage/windows-network-drive_configuration.html#wnd-listen[ our documentation]
